version: '3.5'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app